name: Flask CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the CI job
    
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set Python version (you can specify the version you need)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (ensure you have a testing framework like pytest or unittest)
    - name: Run tests
      run: |
        pytest  # If using pytest, you can replace it with your testing framework
        # If you have a specific test directory, use: pytest tests/

    # Step 5: (Optional) Deploy your Flask app (Heroku example)
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'  # Only deploy on the main branch
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main  # Push the code to Heroku for deployment

